version: "3.7"

services:
  veildb-adminer:
    image: adminer
    container_name: ${IMAGES_PREFIX:-}veildb-adminer
    ports:
      - target: 8080
        published: ${APP_DOCKER_ADMINER_PORT:-8098}
    networks:
      - veildb-network