version: "3.7"

services:
  dbvisor-server:
    container_name: ${IMAGES_PREFIX:-}dbvisor-server
    build:
      context: .
      target: server_prod
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    image: ${IMAGES_PREFIX:-}dbvisor-server
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      SERVER_URL: ${APP_DOCKER_SERVER_URL:-localhost}
      HTTPS_PORT: ${APP_DOCKER_HTTPS_PORT:-8443}
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ${PROJECT_ROOT}:/app
      - ${APP_DOCKER_PATH_DUMP}:/app/backups/backups:delegated
      - ${APP_DOCKER_PATH_CONFIG}:/app/backups/configs:delegated
      - ${APP_DOCKER_LOCAL_BACKUPS_PATH}:/app/backups/local_backups:delegated
      - ${PROJECT_ROOT}/docker/server/certs:/etc/apache2/certs:delegated
    ports:
      # HTTP
      - target: 80
        published: ${APP_DOCKER_HTTP_PORT:-8088}
      # HTTPS
      - target: 443
        published: ${APP_DOCKER_HTTPS_PORT:-8443}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dbvisor-network

  dbvisor-cron-server:
    build:
      context: .
      target: server_cron
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    image: ${IMAGES_PREFIX:-}dbvisor-cron-server
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      SERVER_URL: ${APP_DOCKER_SERVER_URL:-localhost}
      HTTPS_PORT: ${APP_DOCKER_HTTPS_PORT:-8443}
    user: "${DOCKER_UID}:${DOCKER_GID}"
    init: true
    volumes:
      - ${PROJECT_ROOT}:/app
      - ${APP_DOCKER_PATH_DUMP}:/app/backups/backups:delegated
      - ${APP_DOCKER_PATH_CONFIG}:/app/backups/configs:delegated
      - ${APP_DOCKER_LOCAL_BACKUPS_PATH}:/app/backups/local_backups:delegated
      - ${PROJECT_ROOT}/docker/server/certs:/etc/apache2/certs:delegated
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dbvisor-network

networks:
  dbvisor-network:
    name: dbvisor-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${DBVISOR_SUBNET:-172.27.0.0/16}"