version: "3.7"

services:
  dbvisor-server:
    container_name: ${IMAGES_PREFIX:-}dbvisor-server
    build:
      context: .
      target: frankenphp_prod
    image: ${IMAGES_PREFIX:-}dbvisor-server
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      SERVER_NAME: ${APP_DOCKER_SERVER_URL:-localhost}, php:80
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${APP_DOCKER_SERVER_URL:-example\.com|localhost}|php$$
      PHP_VERSION: 8.2
      CADDY_GLOBAL_OPTIONS: ${CADDY_DEBUG:-}
    volumes:
      - ${PROJECT_ROOT}:/app:delegated
      - ${APP_DOCKER_PATH_DUMP}:/app/backups/backups:delegated
      - ${APP_DOCKER_PATH_CONFIG}:/app/backups/configs:delegated
      - ${APP_DOCKER_LOCAL_BACKUPS_PATH}:/app/backups/local_backups:delegated

      # Caddy Volumes
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${APP_DOCKER_HTTP_PORT:-8088}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${APP_DOCKER_HTTPS_PORT:-8443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${APP_DOCKER_HTTP3_PORT:-8443}
        protocol: udp
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dbvisor-network

  dbvisor-cron-server:
    build:
      context: .
      target: frankenphp_cron
    image: ${IMAGES_PREFIX:-}dbvisor-cron-server
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
    init: true
    volumes:
      - ${PROJECT_ROOT}:/app:delegated
      - ${APP_DOCKER_PATH_DUMP}:/app/backups/backups:delegated
      - ${APP_DOCKER_PATH_CONFIG}:/app/backups/configs:delegated
      - ${APP_DOCKER_LOCAL_BACKUPS_PATH}:/app/backups/local_backups:delegated
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dbvisor-network

volumes:
  caddy_data:
  caddy_config:

networks:
  dbvisor-network:
    name: dbvisor-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${DBVISOR_SUBNET:-172.27.0.0/16}"