version: "3.7"

services:
  server_manager:
    build:
      context: .
      target: frankenphp_base
    image: ${IMAGES_PREFIX:-}app-server
    environment:
      APP_SECRET: ${APP_SECRET}
      SERVER_NAME: ${APP_DOCKER_SERVER_URL:-localhost}, php:80
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${APP_DOCKER_SERVER_URL:-example\.com|localhost}|php$$
    volumes:
      - ${PROJECT_ROOT}:/app:delegated
      - ${APP_DOCKER_PATH_DUMP}:/app/backups/dumps:delegated
      - ${APP_DOCKER_PATH_CONFIG}:/app/backups/config:delegated

      # Caddy Volumes
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - db-manager-network

  adminer:
    image: adminer
    ports:
      - 8080:${HTTP_ADMINER_PORT:-8080}
    networks:
      - db-manager-network

volumes:
  caddy_data:
  caddy_config:

networks:
  db-manager-network:
    name: db-manager-network