version: "3.7"

services:
  dbvisor-adminer:
    image: adminer
    container_name: ${IMAGES_PREFIX:-}dbvisor-adminer
    ports:
      - 8080:${APP_DOCKER_ADMINER_PORT:-8080}
    networks:
      - dbvisor-network