# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.service_workspace: '%env(APP_SERVICE_WORKSPACE)%'
    app.service_token: '%env(APP_SERVICE_TOKEN)%'
    app.service_uuid: '%env(APP_SERVER_UUID)%'
    app.service_url: '%env(APP_SERVICE_URL)%'
    app.dump_path: '%env(APP_DUMP_PATH)%'
    app.secret_key_private: '%env(SECRET_KEY_PRIVATE)%'
    env(SECRET_KEY_PRIVATE): '/app/config/keys/private'
    app.secret_key_public: '%env(SECRET_KEY_PUBLIC)%'
    env(SECRET_KEY_PUBLIC): '/app/config/keys/public'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\ServiceApi\AppServiceClient:
        arguments:
            $httpClient: "@Symfony\\Contracts\\HttpClient\\HttpClientInterface"
            $serviceUrl: '%app.service_url%'

    App\Service\Security\Encryption:
        arguments:
            $secretKey: '%app.secret_key_private%'

    App\Service\Security\GenerateKeyPair:
        arguments:
            $secretKey: '%app.secret_key_private%'
            $publicKey: '%app.secret_key_public%'
            $passphrase: ''
            $algorithm: 'RS256'

    App\Service\AppConfig:
        arguments:
            $config: {}

    App\Service\Platform\Custom:
        tags:
        - { name: 'app.platform' }

    App\Service\Platform\PlatformProcessor:
        arguments:
            $platforms: !tagged_iterator 'app.platform'

    App\Service\Engine\EngineProcessor:
        arguments:
            $engines: !tagged_iterator 'app.engine'

    App\Service\Methods\MethodProcessor:
        arguments:
            $methods: !tagged_iterator 'app.backup_method'

    App\Service\Methods\Manual:
        tags:
        - { name: 'app.backup_method' }

    App\Service\Methods\AwsS3:
        tags:
        - { name: 'app.backup_method' }

    App\Service\Methods\Sftp:
        tags:
        - { name: 'app.backup_method' }

#    App\Service\Methods\MethodProcessor:
#        arguments:
#            $methods:
#                - "@App\\Service\\Methods\\Manual"
#                - "@App\\Service\\Methods\\Dump"
#                - "@App\\Service\\Methods\\DumpOverSsh"
#                - "@App\\Service\\Methods\\AwsS3"
#                - "@App\\Service\\Methods\\Sftp"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
