# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.service_workspace: '%env(APP_SERVICE_WORKSPACE)%'
    app.service_token: '%env(APP_SERVICE_TOKEN)%'
    app.service_uuid: '%env(APP_SERVER_UUID)%'
    app.service_secret_key: '%env(APP_SERVER_SECRET_KEY)%'
    app.service_url: '%env(APP_SERVICE_URL)%'
    app.private_keys_path: '%env(APP_KEY_PATH)%'
    app.dump_path: '%env(APP_DUMP_PATH)%'
    app.work_db_user: '%env(WORK_DB_USER)%'
    app.work_db_password: '%env(WORK_DB_PASSWORD)%'
    app.work_db_host: '%env(WORK_DB_HOST)%'
    app.work_db_port: '%env(WORK_DB_PORT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\ServiceApi\AppServiceClient:
        arguments:
            $httpClient: "@Symfony\\Contracts\\HttpClient\\HttpClientInterface"
            $serviceUrl: '%app.service_url%'

    App\Service\Encryption:
        arguments:
            $keyFile: '%app.private_keys_path%'

    App\Service\DumpManagement:
        arguments:
            $dumpPath: '%app.dump_path%'

    App\Service\AppConfig:
        arguments:
            $config: {
                work_db_user: '%app.work_db_user%',
                work_db_password: '%app.work_db_password%',
                work_db_host: '%app.work_db_host%',
                work_db_port: '%app.work_db_port%',
            }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
