version: '3.7'

services:
  # -------------- #
  # -- Database -- #
  # -------------- #
  dbvisor-mysql:
    image: mariadb:${MARIA_DB_VERSION:-latest}
    container_name: ${IMAGES_PREFIX:-}dbvisor-mysql
    command: --max_allowed_packet=64M
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-root}
    ports:
      - ${DATABASE_PORT:-3306}:3306
    expose:
      - ${DATABASE_PORT:-3306}
    init: true
    networks:
      - dbvisor-network

networks:
  dbvisor-network:
    external: true
    name: dbvisor-network