version: '3.7'

services:
  # -------------- #
  # -- Database -- #
  # -------------- #
  dbvisor-postgres:
    image: postgres:${POSTGRES_DB_VERSION:-latest}
    container_name: ${IMAGES_PREFIX:-}dbvisor-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-root}
    ports:
      - ${DATABASE_PORT:-5432}:5432
    expose:
      - ${DATABASE_PORT:-5432}
    init: true
    networks:
      - dbvisor-network

networks:
  dbvisor-network:
    external: true
    name: dbvisor-network