version: '3.7'

services:
  # -------------- #
  # -- Database -- #
  # -------------- #
  veildb-postgres:
    image: postgres:${POSTGRES_DB_VERSION:-latest}
    container_name: ${IMAGES_PREFIX:-}veildb-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-root}
      PGPORT: ${DATABASE_PORT:-5432}
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}
    expose:
      - ${DATABASE_PORT:-5432}
    init: true
    networks:
      - veildb-network

networks:
  veildb-network:
    external: true
    name: veildb-network